Use projects not setwd
swcarpentry/r-novice-inflammation pull request #515
Opened 2021-04-14 23:42 UTC by Alanocallaghan

Address #512

2021-04-14 23:42 UTC, Alanocallaghan commented
I realise I've done this a bit backwards and the project setup should prob be in setup.md. Oops!

2021-04-19 00:32 UTC, HaoZeke requested changes
Looks great to me! Thanks for this. I made some minor suggestions, but otherwise this is fantastic.

2021-04-19 00:32 UTC, HaoZeke commented on _episodes_rmd/01-starting-with-data.Rmd
> +# Getting started
Perhaps this should be ## here?
```suggestion
## Getting started
```

Otherwise the lower headings need to go up one level as well...

2021-04-19 00:32 UTC, HaoZeke commented on _episodes_rmd/01-starting-with-data.Rmd
> +Now that we are set up with an Rstudio project, we can be sure the data
```suggestion
Now that we are set up with an Rstudio project, we are sure that the
```

2021-04-19 16:49 UTC, HaoZeke approved these changes
Thanks for the changes, looks great!

2021-04-19 16:50 UTC, merged

2021-04-19 17:00 UTC, Alanocallaghan commented
Thanks!